'use strict';
const DATA=JSON.parse(document.getElementById('architecture-data').textContent);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let current='01', section='architecture', tab='diagram', zoom=1, baseWidth=0,baseHeight=0, toastTimer;
const content=document.getElementById('content');
const getView=()=>DATA.diagrams.find(d=>d.id===current);
const refLink=k=>`<a href="${esc(DATA.sources[k].url)}" target="_blank" rel="noopener noreferrer">${esc(DATA.sources[k].title)} ↗</a>`;
function toast(s){const t=document.getElementById('toast');t.textContent=s;t.style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.style.display='none',3300)}
function renderNav(q=''){q=q.toLowerCase().trim();let last='',out='';for(const d of DATA.diagrams){if(q&&!(`${d.id} ${d.title} ${d.group} ${d.question} ${d.code}`.toLowerCase().includes(q)))continue;if(last!==d.group){out+=`<div class="navgroup">${esc(d.group)}</div>`;last=d.group}out+=`<button class="navbtn ${d.id===current&&section==='architecture'?'active':''}" data-view="${d.id}" ${d.id===current?'aria-current="page"':''}><span class="num">${d.id}</span><span>${esc(d.title)}</span></button>`}document.getElementById('nav').innerHTML=out||'<p style="padding:10px;color:#acbfce;font-size:12px">No matching views.</p>'}
function downloadText(text,name,type='text/plain'){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),5000)}
function slug(d){return `${d.id}-${d.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/-$/,'')}`}
function setSection(s){section=s;closeNavigation();document.getElementById('sectionCrumb').textContent=({architecture:'Architecture',hardware:'Hardware & sizing',catalog:'Automation & acceptance',sources:'Sources & assumptions'})[s];document.querySelectorAll('[data-section]').forEach(b=>b.classList.toggle('active',b.dataset.section===s));renderNav(document.getElementById('navSearch').value);if(s==='architecture')renderArchitecture();if(s==='hardware')renderHardware();if(s==='catalog')renderCatalog();if(s==='sources')renderSources()}
function selectView(id){if(!DATA.diagrams.some(d=>d.id===id))return;current=id;tab='diagram';try{history.replaceState(null,'','#'+id)}catch(e){}setSection('architecture')}
function refs(d){return d.refs.length?`<div class="sourcesinline"><h3>Primary references</h3>${d.refs.map(refLink).join('')}</div>`:''}
function renderArchitecture(){const d=getView();content.innerHTML=`
 <div class="kicker">${esc(d.group)} / VIEW ${d.id}</div><h1 class="viewtitle">${esc(d.title)}</h1><p class="question">${esc(d.question)}</p><p class="summary">${esc(d.summary)}</p>
 <section class="diagramcard" id="diagramCard" aria-label="Diagram ${d.id}">
 <div class="cardtabs"><div class="subtabs"><button class="subtab ${tab==='diagram'?'active':''}" data-tab="diagram">Diagram</button><button class="subtab ${tab==='notes'?'active':''}" data-tab="notes">Design notes</button><button class="subtab ${tab==='source'?'active':''}" data-tab="source">Mermaid source</button></div><div class="navbuttons"><button class="btn" id="prev" aria-label="Previous diagram" ${d.id==='01'?'disabled':''}>← <span class="nav-word">Previous</span></button><button class="btn" id="next" aria-label="Next diagram" ${d.id==='18'?'disabled':''}><span class="nav-word">Next</span> →</button></div></div>
 <div id="diagramBody"></div></section>
 <div class="under"><div class="callout"><strong>Design boundary</strong>${esc(d.notes[0])}</div><div class="related"><strong>Related views</strong><br>${d.related.map(id=>{const v=DATA.diagrams.find(x=>x.id===id);return `<button class="relatedbtn" data-view="${id}">${id} · ${esc(v.title)}</button>`}).join('')}</div></div>
 <div class="footer">Proposed design, not an as-built inventory. Hardware, software versions, entitlements, failure domains and service targets require validation. The SVG and Mermaid source describe the same view.</div>`;
 document.getElementById('prev').onclick=()=>selectView(String(Number(current)-1).padStart(2,'0'));
 document.getElementById('next').onclick=()=>selectView(String(Number(current)+1).padStart(2,'0'));
 renderBody();
}
function renderBody(){const d=getView(),body=document.getElementById('diagramBody');document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));
 if(tab==='notes'){body.innerHTML=`<div class="panel"><h3>Decisions, assumptions and failure boundaries</h3><div class="noteslist">${d.notes.map((n,i)=>`<div class="noterow"><span class="notenum">${String(i+1).padStart(2,'0')}</span><p>${esc(n)}</p></div>`).join('')}</div>${refs(d)}</div>`;return}
 if(tab==='source'){body.innerHTML=`<div class="panel"><div class="sourcehead"><div><h3>Editable Mermaid source</h3><p style="margin:0;font-size:11px">Copy or export this source for editing. This viewer does not compile source changes.</p></div><div class="tools"><button class="btn" id="copySource">Copy code</button><button class="btn primary" id="exportMmd">Export .mmd</button></div></div><textarea readonly spellcheck="false" class="code" id="mermaidCode" aria-label="Mermaid source code"></textarea></div>`;document.getElementById('mermaidCode').value=d.code;document.getElementById('exportMmd').onclick=()=>downloadText(d.code,slug(d)+'.mmd');document.getElementById('copySource').onclick=async()=>{try{await navigator.clipboard.writeText(d.code);toast('Mermaid source copied')}catch(e){const c=document.getElementById('mermaidCode');c.focus();c.select();try{if(document.execCommand('copy'))toast('Mermaid source copied');else toast('Source selected. Press Ctrl/Cmd+C to copy.')}catch(e){toast('Source selected. Press Ctrl/Cmd+C to copy.')}}};return}
 body.innerHTML=`<div class="toolbar"><div class="tools"><button class="btn" id="zoomOut" aria-label="Zoom out">−</button><span class="zoomlabel" id="zoomLabel">100%</span><button class="btn" id="zoomIn" aria-label="Zoom in">+</button><button class="btn" id="fit">Fit</button><button class="btn" id="readSize">Read size</button><button class="btn" id="fullscreen">Fullscreen</button></div><div class="tools"><span class="hint">Drag to pan · Ctrl/⌘ + wheel to zoom</span><button class="btn" id="exportSvg" aria-label="Export SVG">SVG ↓</button><button class="btn primary" id="downloadMmd" aria-label="Export Mermaid">Mermaid ↓</button></div></div><div class="viewport" id="viewport" tabindex="0" aria-label="Scrollable diagram. Use Read size for full-size labels."><div class="stage" id="stage">${d.svg}</div></div><div class="inspector" id="inspector"></div><div class="legendbar"><span class="key"><i class="swatch ai"></i>AI reasoning</span><span class="key"><i class="swatch control"></i>Policy / control</span><span class="key"><i class="swatch infra"></i>Infrastructure</span><span class="key"><i class="swatch data"></i>Data / state</span><span class="key"><i class="swatch human"></i>Human authority</span><span class="key"><i class="swatch stop"></i>Stop / exception</span><span>Use <b>Read size</b> for readable labels; Fit shows the whole view.</span></div>`;
 const svg=document.querySelector('#stage svg');const vb=svg.viewBox.baseVal;baseWidth=vb.width;baseHeight=vb.height;svg.removeAttribute('style');svg.setAttribute('role','img');svg.setAttribute('aria-label',d.title);svg.style.maxWidth='none';
 document.getElementById('zoomIn').onclick=()=>changeZoom(zoom*1.25);
 document.getElementById('zoomOut').onclick=()=>changeZoom(zoom/1.25);
 document.getElementById('fit').onclick=fit;
 document.getElementById('readSize').onclick=()=>{changeZoom(1);toast('Full-size labels. Scroll or drag to explore the diagram.')};
 document.getElementById('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.getElementById('diagramCard').requestFullscreen();setTimeout(fit,100)}catch(e){toast('Fullscreen is unavailable in this browser. Use the browser full-screen shortcut.')}};
 document.getElementById('exportSvg').onclick=()=>downloadText(d.svg,slug(d)+'.svg','image/svg+xml');
 document.getElementById('downloadMmd').onclick=()=>downloadText(d.code,slug(d)+'.mmd');
 const vp=document.getElementById('viewport');let drag=null,moved=false;
 vp.addEventListener('pointerdown',e=>{if(e.button!==0)return;drag={x:e.clientX,y:e.clientY,l:vp.scrollLeft,t:vp.scrollTop};moved=false;vp.classList.add('dragging');});
 vp.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>5){moved=true;if(!vp.hasPointerCapture(e.pointerId))vp.setPointerCapture(e.pointerId)}vp.scrollLeft=drag.l-dx;vp.scrollTop=drag.t-dy});
 vp.addEventListener('pointerup',e=>{drag=null;vp.classList.remove('dragging');if(vp.hasPointerCapture(e.pointerId))vp.releasePointerCapture(e.pointerId)});
 vp.addEventListener('pointercancel',()=>{drag=null;vp.classList.remove('dragging')});
 vp.addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey){e.preventDefault();changeZoom(zoom*(e.deltaY<0?1.12:1/1.12))}},{passive:false});
 svg.addEventListener('click',e=>{if(moved)return;const n=e.target.closest('.node');if(!n)return;svg.querySelectorAll('.selected').forEach(x=>x.classList.remove('selected'));n.classList.add('selected');const txt=(n.querySelector('.label')||n).textContent.replace(/\s+/g,' ').trim();document.getElementById('inspector').innerHTML=`<strong>Selected component:</strong> ${esc(txt)} <span style="color:#a0b2c7"> · Review the Design notes tab for this view's authority and failure boundaries.</span>`});
 requestAnimationFrame(fit);
}
function changeZoom(z){const vp=document.getElementById('viewport'),s=document.querySelector('#stage svg');if(!vp||!s)return;const old=zoom||1,cx=(vp.scrollLeft+vp.clientWidth/2)/old,cy=(vp.scrollTop+vp.clientHeight/2)/old;zoom=Math.max(.12,Math.min(3,z));s.setAttribute('width',String(baseWidth*zoom));s.setAttribute('height',String(baseHeight*zoom));s.style.width=baseWidth*zoom+'px';s.style.height=baseHeight*zoom+'px';document.getElementById('zoomLabel').textContent=Math.round(zoom*100)+'%';vp.scrollLeft=Math.max(0,cx*zoom-vp.clientWidth/2);vp.scrollTop=Math.max(0,cy*zoom-vp.clientHeight/2)}
function fit(){const vp=document.getElementById('viewport');if(!vp)return;changeZoom(Math.min((vp.clientWidth-65)/baseWidth,(vp.clientHeight-65)/baseHeight,1));vp.scrollLeft=0;vp.scrollTop=0}
function renderHardware(){content.innerHTML=`<div class="kicker">Procurement worksheet / Arithmetic is not a benchmark</div><h1 class="viewtitle">Hardware, model fit and resilience</h1><p class="summary">Choose a checkpoint and service target first. Distinguish a development machine, a complete production model replica and a second replica for failure capacity.</p><div class="callout"><strong>Recommended purchasing sequence</strong>Start with one development platform and a representative test environment. For a mandatory full-model service, evaluate an OEM multi-GPU server against your actual workflows before ordering a cluster. Buy independently usable capacity when the required service must survive a complete replica failure.</div><div class="cards">${DATA.hardware.map(h=>`<article class="infocard"><span class="pill">${esc(h.tier)}</span><h3>${esc(h.name)}</h3><div class="mem">${esc(h.memory)}</div><p>${esc(h.fit)}</p><p><strong>Constraint:</strong> ${esc(h.caution)}</p><div class="smalllink">${refLink(h.ref)}</div></article>`).join('')}</div>
<div class="section"><h2>R1-671B: a named worked example</h2><p>The original full DeepSeek-R1 has 671 billion total parameters. It is the historical sizing example here, <strong>not a claim that R1 is the latest or best model for these workflows</strong>. The newer DeepSeek-V4.1-Flash model has a different architecture; inspect its complete checkpoint and runtime residency independently.</p><div class="tablewrap"><table><thead><tr><th>Nominal representation</th><th>Theoretical weights only</th><th>Not included</th></tr></thead><tbody><tr><td>4-bit</td><td>335.5 GB</td><td>Quantization metadata, KV cache, runtime buffers and headroom</td></tr><tr><td>8-bit</td><td>671 GB</td><td>Same exclusions; actual checkpoint may be mixed precision</td></tr><tr><td>16-bit</td><td>1,342 GB</td><td>Same exclusions; decimal GB, not GiB</td></tr></tbody></table></div><p class="smalllink">${refLink('r1')} &nbsp; ${refLink('deepseek_current')}</p><div class="callout warn"><strong>Active parameters do not determine total weight storage.</strong>Two 128 GB devices have 256 GB nominal aggregate memory, below R1's theoretical 335.5 GB 4-bit weights alone. Four have 512 GB nominal, but do not automatically become one usable 512 GB accelerator. Model sharding needs supported software, communication and memory placement.</div></div>
<div class="section"><h2>Capacity lower-bound calculator</h2><p>This is transparent arithmetic, not a hardware configurator. The extra-memory budget below is an illustrative input you must replace with measurements. It does not estimate KV cache from context length.</p><div class="calcgrid"><label>Total parameters, billions<input id="params" type="number" min="0.1" step="0.1" value="671"></label><label>Nominal bits per parameter<select id="bits"><option value="4">4-bit</option><option value="8">8-bit</option><option value="16">16-bit</option></select></label><label>Additional memory budget, GB<input id="extra" type="number" min="0" step="1" value="128"></label><label>Usable memory per GPU, GB<input id="deviceMem" type="number" min="1" step="1" value="260"></label><label>GPUs per supported server topology<input id="gpuSlots" type="number" min="1" max="128" step="1" value="8"></label><label>Independent complete model replicas<input id="replicas" type="number" min="1" max="100" step="1" value="2"></label></div><div class="outputs"><div class="output"><span>Theoretical weights only</span><strong id="outWeights">—</strong><span>GB, decimal</span></div><div class="output"><span>Weights + manual reserve</span><strong id="outPool">—</strong><span>GB per complete model replica</span></div><div class="output"><span>Memory-only device lower bound</span><strong id="outDevices">—</strong><span>Not a supported topology recommendation</span></div><div class="output"><span>Topology-rounded servers</span><strong id="outServers">—</strong><span id="serverCaption">Across all requested replicas</span></div></div><p id="calcerror" class="calcerror" role="status"></p><div class="formula">weight_GB = parameter_billions × bits / 8<br>capacity_lower_bound = ceil((weight_GB + manual_reserve_GB) / usable_device_GB)<br>servers_total = ceil(capacity_lower_bound / GPUs_per_server) × replicas</div><p>The default 260 GB usable-memory input is a planning assumption, not a vendor guarantee. Check quantization kernels, model architecture, shard layout, per-device imbalance, runtime overhead, interconnect, context length, concurrency, throughput and failure capacity before procurement.</p></div>
<div class="section"><h2>Procurement gates</h2><div class="testgrid"><div class="test"><b>01 / MODEL AND TASKS</b>Pin checkpoint, tokenizer, license, quantization, driver and runtime. Benchmark actual administrative tasks and tool correctness, not only public model scores.</div><div class="test"><b>02 / SERVICE TARGET</b>Define concurrency, input and output distributions, context length, p95 completion latency and acceptable degraded capability.</div><div class="test"><b>03 / FACILITIES AND SUPPORT</b>Validate rack power, cooling, supported chassis, spares, network paths, OEM maintenance and warranty terms.</div><div class="test"><b>04 / RECOVERY</b>Test a complete replica loss, independent management recovery, denied internet egress and the absence of customer-data leakage.</div></div><p>Exact prices, availability and a final bill of materials are intentionally not invented. These need an OEM quote for the validated configuration.</p></div>`;
 ['params','bits','extra','deviceMem','gpuSlots','replicas'].forEach(id=>document.getElementById(id).addEventListener('input',calculate));calculate();}
function calculate(){const val=id=>Number(document.getElementById(id).value);const p=val('params'),b=val('bits'),e=val('extra'),m=val('deviceMem'),g=val('gpuSlots'),r=val('replicas');if(['params','bits','extra','deviceMem','gpuSlots','replicas'].some(id=>!document.getElementById(id).value.trim())||![p,b,e,m,g,r].every(Number.isFinite)||p<=0||b<=0||e<0||m<=0||g<1||r<1||!Number.isInteger(g)||!Number.isInteger(r)){['outWeights','outPool','outDevices','outServers'].forEach(id=>document.getElementById(id).textContent='—');document.getElementById('serverCaption').textContent='Correct the inputs to calculate.';document.getElementById('calcerror').textContent='Enter positive values and whole numbers for topology size and replicas.';return}document.getElementById('calcerror').textContent='';const w=p*b/8,n=Math.ceil((w+e)/m),s=Math.ceil(n/g);const fmt=x=>x.toLocaleString('en-US',{maximumFractionDigits:1});document.getElementById('outWeights').textContent=fmt(w);document.getElementById('outPool').textContent=fmt(w+e);document.getElementById('outDevices').textContent=n;document.getElementById('outServers').textContent=s*r;document.getElementById('serverCaption').textContent=`${s} server(s) per replica × ${r} replicas. Capacity arithmetic only.`}
function renderCatalog(){content.innerHTML=`<div class="kicker">Custom workflows / Scoped authority</div><h1 class="viewtitle">Automation catalog and acceptance gates</h1><p class="summary">The platform is a collection of tested workflows and adapters, not a single prompt with administrator credentials. These are workflow specifications, not a claim that the integrations are already implemented.</p><div class="section"><h2>Administrative and security coverage</h2><div class="tablewrap"><table><thead><tr><th>Capability and trigger</th><th>Bounded autonomous work</th><th>Approval / human boundary</th><th>Independent verification</th></tr></thead><tbody>${DATA.catalog.map(r=>`<tr><td>${esc(r[0])}<br><span style="font-weight:normal;color:#a0b2c7;font-size:10px">${esc(r[1])}</span></td><td>${esc(r[2])}</td><td>${esc(r[3])}</td><td>${esc(r[4])}</td></tr>`).join('')}</tbody></table></div></div><div class="section"><h2>Representative end-to-end acceptance tests</h2><p>These tests exercise actual failure and authorization boundaries. They complement unit tests, model evaluations and vendor compatibility checks.</p><div class="testgrid">${DATA.acceptance.map((t,i)=>`<div class="test"><b>TEST ${String(i+1).padStart(2,'0')}</b>${esc(t)}</div>`).join('')}</div></div><div class="section"><h2>Rollout by proven authority, not model confidence</h2><div class="testgrid"><div class="test"><b>01 / READ-ONLY</b>Inventory, dependency mapping, evidence retrieval, recommendations and operator comparisons.</div><div class="test"><b>02 / REPRESENTATIVE LAB</b>Real adapters on disposable infrastructure; failure, recovery, injection and tenant-isolation tests.</div><div class="test"><b>03 / SUPERVISED PRODUCTION</b>Exact-plan approvals, narrow canaries, monitored outcomes and tested compensation paths.</div><div class="test"><b>04 / BOUNDED AUTONOMY</b>Pre-approved repeatable tasks. Keep human incident ownership, physical support and independent recovery authority.</div></div></div>`}
function renderSources(){content.innerHTML=`<div class="kicker">Evidence and scope / 18 September 2026</div><h1 class="viewtitle">Assumptions, boundaries and primary sources</h1><p class="summary">The architecture is a proposed design. Vendor specifications below support factual constraints; they do not certify this whole solution or guarantee model performance.</p><div class="section"><h2>Design assumptions</h2>${DATA.assumptions.map(a=>`<h3>${esc(a[0])}</h3><p>${esc(a[1])}</p>`).join('')}</div><div class="section"><h2>Primary references</h2>${Object.entries(DATA.sources).map(([k,s])=>`<div class="sourcerow">${refLink(k)}<p>${esc(s.supports)}</p></div>`).join('')}</div><div class="callout"><strong>Viewer privacy</strong>This standalone file uses pre-rendered SVG and local JavaScript. It makes no runtime network calls and includes no CDN, analytics, external fonts or remote Mermaid renderer. Source links contact their websites only when clicked. The viewer does not operate any infrastructure.</div>`}
function syncNavigation(){const small=matchMedia('(max-width:760px)').matches;const open=document.body.classList.contains('nav-open');document.getElementById('sidebar').inert=small&&!open;document.querySelector('main').inert=small&&open;}
function closeNavigation(){document.body.classList.remove('nav-open');document.getElementById('menuToggle').setAttribute('aria-expanded','false');syncNavigation();}
function openNavigation(){document.body.classList.add('nav-open');document.getElementById('menuToggle').setAttribute('aria-expanded','true');syncNavigation();document.getElementById('navSearch').focus();}
document.getElementById('menuToggle').onclick=openNavigation;
document.getElementById('closeNav').onclick=document.getElementById('scrim').onclick=()=>{closeNavigation();document.getElementById('menuToggle').focus();};
matchMedia('(max-width:760px)').addEventListener('change',syncNavigation);
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('nav-open')){e.preventDefault();closeNavigation();document.getElementById('menuToggle').focus();}if(e.key==='/'&&!/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)){e.preventDefault();if(matchMedia('(max-width:760px)').matches)openNavigation();else document.getElementById('navSearch').focus();}if(e.key==='Tab'&&document.body.classList.contains('nav-open')){const els=[...document.querySelectorAll('#sidebar button:not(:disabled),#sidebar input,#sidebar a')].filter(el=>el.offsetParent!==null);const first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
document.addEventListener('click',e=>{const v=e.target.closest('[data-view]');if(v){selectView(v.dataset.view);return}const st=e.target.closest('[data-section]');if(st){setSection(st.dataset.section);return}const t=e.target.closest('[data-tab]');if(t){tab=t.dataset.tab;renderBody()}});
document.getElementById('navSearch').addEventListener('input',e=>renderNav(e.target.value));
document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||section!=='architecture')return;if(e.key==='ArrowRight'&&Number(current)<18){e.preventDefault();selectView(String(Number(current)+1).padStart(2,'0'))}if(e.key==='ArrowLeft'&&Number(current)>1){e.preventDefault();selectView(String(Number(current)-1).padStart(2,'0'))}});
window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(DATA.diagrams.some(d=>d.id===id))selectView(id)});
const initial=location.hash.slice(1);if(DATA.diagrams.some(d=>d.id===initial))current=initial;
renderNav();setSection('architecture');
window.architectureExplorer={selectView,setSection,DATA};
